### ISSUE TITLE
Improvements suggested by StevenGJ

### ISSUE THREAD

**Issue by KronosTheLate** [KronosTheLate/FresnelEquations.jl#1]
@stevengj
> It seems like you implemented every function twice, once for the complex coefficient and once for its absolute value squared. Why not have the latter simply call the former?

Done

> You also calculate `T_p` via `1 - R_p`, which may suffer catastrophic cancellation if the reflectance is close to one. Using `abs2(t_p)` via your `t_p` function avoids this.

In making the previous change, I did this. However, I noticed that `T_s` and `T_p` are now off by a factor of almost 2 (but not quite) from satisfying conservation of energy. 
```
julia> let
           n1 = 1
           n2 = 2
           θ_i = deg2rad(10)
           @show R_s(n1, n2, θ_i)
           @show T_s(n1, n2, θ_i)
           @show R_p(n1, n2, θ_i)
           @show T_p(n1, n2, θ_i)
           nothing
       end
R_s(n1, n2, θ_i) = 0.11454557997889622
T_s(n1, n2, θ_i) = 0.43765391958146965
R_p(n1, n2, θ_i) = 0.10771599997760896
T_p(n1, n2, θ_i) = 0.44102957889162075
```

This of course relies on the underlying `t` coefficients. But they are taken straight from the wikipedia article:
```
function t_s(n₁, n₂, θᵢ, θₜ)
    num = 2n₁ * cos(θᵢ)
    den = n₁ * cos(θᵢ) + n₂ * cos(θₜ)
    return num / den
end

function t_p(n₁, n₂, θᵢ, θₜ)
    num = 2n₁ * cos(θᵢ)
    den = n₂ * cos(θᵢ) + n₁ * cos(θₜ)
    return num / den
end
```

So there is an error in the wikipedia-article, my copying of them, or your suggested `abs2(t_p)`. Actual code below:
```
T_s(n₁, n₂, θᵢ, θₜ) = abs2(t_s(n₁, n₂, θᵢ, θₜ))
T_p(n₁, n₂, θᵢ, θₜ) = abs2(t_p(n₁, n₂, θᵢ, θₜ))
```

So do you have a suggestion as for what to do? Perhaps you have/know of a test-set that can verify the coefficients for some test-case, where all the expected outputs are known?

**Comment by stevengj** [comment]
Sorry, I forgot that the definition of the complex t is a bit different.  As summarized in WP:
<img width="1162" alt="image" src="https://github.com/KronosTheLate/FresnelEquations.jl/assets/2913679/98e842b6-f54a-4f42-ba7e-e92e6ba4e672">

**Comment by KronosTheLate** [comment]
It should all be well and good now ^_^
